(function() {
  Ext.define('stable_mobile.model.Horse', {
    extend: 'Ext.data.Model',
    config: {
      fields: [
        {
          name: 'id',
          type: 'int'
        }, {
          name: 'name',
          type: 'auto'
        }, {
          name: 'show_name',
          type: 'auto'
        }, {
          name: 'display_name',
          type: 'auto'
        }, {
          name: 'img',
          type: 'auto'
        }, {
          name: 'thumb',
          type: 'auto'
        }, {
          name: 'gender',
          type: 'auto'
        }, {
          name: 'prescriptions',
          type: 'auto'
        }, {
          name: 'display_height',
          type: 'auto'
        }, {
          name: 'breed',
          type: 'auto'
        }, {
          name: 'age',
          type: 'auto'
        }, {
          name: 'owner',
          type: 'auto'
        }, {
          name: 'usef_number',
          type: 'auto'
        }, {
          name: 'passport_number',
          type: 'auto'
        }, {
          name: 'coggins_date',
          type: 'auto'
        }, {
          name: 'last_coggins_date',
          type: 'auto'
        }, {
          name: 'passport_renewal_date',
          type: 'auto'
        }, {
          name: 'color',
          type: 'auto'
        }, {
          name: 'markings',
          type: 'auto'
        }, {
          name: 'tattoo',
          type: 'auto'
        }, {
          name: 'brand',
          type: 'auto'
        }, {
          name: 'sire',
          type: 'auto'
        }, {
          name: 'dam_sire',
          type: 'auto'
        }, {
          name: 'dam',
          type: 'auto'
        }, {
          name: 'fei_number',
          type: 'auto'
        }, {
          name: 'fei_renewal_date',
          type: 'auto'
        }, {
          name: 'insurance',
          type: 'auto'
        }, {
          name: 'lease',
          type: 'auto'
        }, {
          name: 'vices',
          type: 'auto'
        }, {
          name: 'allergies',
          type: 'auto'
        }, {
          name: 'comments',
          type: 'auto'
        }, {
          name: 'equipment_notes',
          type: 'auto'
        }, {
          name: 'prep_notes',
          type: 'auto'
        }, {
          name: 'ushja_number',
          type: 'auto'
        }, {
          name: 'measurement_card_number',
          type: 'auto'
        }, {
          name: 'breed_registration_number',
          type: 'auto'
        }, {
          name: 'registration_number_notes',
          type: 'auto'
        }, {
          name: 'purchase_date',
          type: 'auto'
        }, {
          name: 'sale_date',
          type: 'auto'
        }, {
          name: 'sale_price',
          type: 'auto'
        }, {
          name: 'departure_date',
          type: 'auto'
        }, {
          name: 'am_meal',
          type: 'auto'
        }, {
          name: 'lunch_meal',
          type: 'auto'
        }, {
          name: 'pm_meal',
          type: 'auto'
        }, {
          name: 'night_meal',
          type: 'auto'
        }, {
          name: 'documents',
          type: 'auto'
        }
      ]
    }
  });

}).call(this);
